### ISSUE TITLE
Incorrect long formatting for just Any pronouns

### ISSUE THREAD

**Issue by RuiNtD** [cyyynthia/pronoundb.org#101]
Setting pronouns to just "Any pronouns" causes the long formatting to be grammatically incorrect.

![image](https://github.com/cyyynthia/pronoundb.org/assets/1149870/66979555-7dd5-4468-a17c-5f7cfbc30416)

"Goes by or any pronouns" should just be "Goes by any pronouns"

**Comment by cyyynthia** [comment]
This has already been fixed a while ago, just not deployed yet due to ongoing work on new features. The extension should have correct formatting since 0.14.1.
