### ISSUE TITLE
Human-readable pronouns in API?

### ISSUE THREAD

**Issue by RuiNtD** [cyyynthia/pronoundb.org#102]
With the introduction of multiple sets of pronouns, it would be really nice to have an API endpoint that just returns the human-readable pronouns (what's shown on the website) in the normal, short, and long formats; so that developers don't have to write the code to generate these strings or copy your code. Something like this:

```json
{
  "normal": "he/they/any",
  "short": "he/they",
  "long": "Goes by \"he/him\", \"they/them\", or any pronouns"
}
```

**Comment by cyyynthia** [comment]
I will close this for the same rationale as #23. It is not the role of an API to be the presentation layer and as such it will not be one.
