### ISSUE TITLE
Better Discord don't work with the plugin

### ISSUE THREAD

**Issue by z9ctn4fn** [cyyynthia/pronoundb.org#104]
here's the log file
[discord.com-1687307520098.log](https://github.com/cyyynthia/pronoundb.org/files/11810742/discord.com-1687307520098.log)

**Comment by cyyynthia** [comment]
Hey there, I am not the developer of the BetterDiscord addon, and this repository is not the place to report issues with third party plugins.

You should report this to the appropriate repository, so the dev of the addon can fix your problem.

**Comment by z9ctn4fn** [comment]
Oh, sorry.
