### ISSUE TITLE
Adding support for Kick

### ISSUE THREAD

**Issue by MrNamelessKnight** [cyyynthia/pronoundb.org#105]
As [Kick ](https://kick.com) is a streaming platform (it's like twitch), it would be cool to get pronouns on it with this extension.

**Comment by cyyynthia** [comment]
The ~~money laundering machine~~ streaming platform financed by Stake's cryptocurrency gambling business does not provide the necessary API endpoints to make an integration. I can't make an integration for it without an OAuth authentication endpoint.
