### ISSUE TITLE
Neopronoun Text Entry (Enhancement)

### ISSUE THREAD

**Issue by ColdStoneSys** [cyyynthia/pronoundb.org#112]
Rather than being forced to choose the "other" option myself and others I'm sure would like a field to enter our own neopronouns. Of course this does come at the cost of need for moderation. Perhaps an approval process after saving changes and then if they are approved they will appear on supported apps/sites.

**Comment by NoPlagiarism** [comment]
https://github.com/cyyynthia/pronoundb.org?tab=readme-ov-file#neo-pronouns-support

#96
