### ISSUE TITLE
Add Support for Guilded

### ISSUE THREAD

**Issue by 0J3** [cyyynthia/pronoundb.org#25]
It would be nice to have some support for [guilded.gg](https://guilded.gg/), although most users use it's desktop app, meaning it might be a bit more difficult to add support for, until it has something like [BandagedBD](https://betterdiscord.app/) made for it

**Comment by cyyynthia** [comment]
Guilded doesn't seem provide any way of doing oauth, which is necessary for support. Unless they implement oauth as part of their upcoming "bot api", this won't be feasible.

I'll close this for now, and will come back to it if guilded implements the necessary things.
