### ISSUE TITLE
Add betterdiscord plugin link to website?

### ISSUE THREAD

**Issue by forever-and-a-day** [cyyynthia/pronoundb.org#28]
BetterDiscord (discord modified application) now has a PronounDB plugin to see pronouns directly in the application, would be neat to link it on the main page or a subpage on pronoundb.org! Not sure if this is out of scope just lemme know :)
Link: https://betterdiscord.app/plugin/PronounDB

**Comment by cyyynthia** [comment]
I'm aware it exists; just like the Powercord plugin it will not be listed on the website.
