### ISSUE TITLE
Add support for VRChat

### ISSUE THREAD

**Issue by tetra-fox** [cyyynthia/pronoundb.org#29]
I write a mod for VRChat called ProPlates which serves a similar function to pronounDB, and I was wondering if you would consider adding VRChat integration to pronounDB. I could then use the API to get and assign pronouns to players in-game, rather than using my current method of parsing the user's bio for their pronouns which requires them to be formatted in a specific way.

There is one caveat to this, however. VRChat doesn't publicly offer SSO. I only know of one instance where they have allowed this, and it required VRChat to work closely with the third party. That wouldn't be a problem, but you have to consider that VRChat doesn't officially support modding, which greatly decreases the chances of them agreeing to work with pronounDB.

I have a potential solution to this though: they have a website that can be used for the social functions of the game, and that could be the reasoning behind the need for integration.

A user of my mod brought this up to me, and you can see the original issue here: https://github.com/tetra-fox/VRCMods/issues/1, where I described an alternative solution (manual ID entry) in the case that VRChat doesn't allow pronounDB to use their SSO.

**Comment by cyyynthia** [comment]
Hello,

Sorry for the months of silence from me on this issue. Unfortunately, if VRChat doesn't offer a way for me to authenticate user accounts strongly (via OAuth, or any other authentication protocol) I won't be able to let people link their VRChat accounts to PronounDB. I do not want to allow loose account linking by entering your own ID, as this can cause many issues and be abused for evil intents.

I also highly doubt VRChat will accept access request from me on these grounds, and if it's to end up having to do what VRChat wants me to do under the "working closely with" umbrella, it's a no-go.

I don't think integration will be possible on this one, unfortunately. I'll be closing this issue.

**Comment by tetra-fox** [comment]
Understandable, figured it was worth a shot, but thanks for getting back to me regardless!
