### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by skyeredwood** [cyyynthia/pronoundb.org#31]
I'm trying to open pronoundb.org but I get this error after about a minute waiting for it to load:
```json
{"statusCode":500,"error":"Internal Server Error","message":"connect ECONNREFUSED 127.0.0.1:27017"}
```

The 27017 port suggest it's a Mongo error. Any idea what's happening?

**UPDATE: It now throws a 502 but Cloudflare Always Online is showing a rollback from the Wayback Machine - login functionality doesn't work however.**

**Comment by hanatic** [comment]
Looking at the `:27017` port, it's probably an issue with MongoDB.

**Comment by skyeredwood** [comment]
Resolved, PronounDB is back online.

**Comment by yeSpud** [comment]
Looks like this is an issue again
<img width="1792" alt="Screen Shot 2021-11-07 at 14 58 21" src="https://user-images.githubusercontent.com/10385195/140665172-75806944-8393-4a5b-a3ed-5b49096adc1c.png">
