### ISSUE TITLE
add support for neopronouns

### ISSUE THREAD

**Issue by lunaaaaaaaa413** [cyyynthia/pronoundb.org#35]
i cant imagine this would be too hard, you would just need a "custom" option where you can put your own pronouns in a text box

**Comment by Toby222** [comment]
https://github.com/cyyynthia/pronoundb.org#neo-pronouns-andor-custom-pronouns-support

**Comment by cyyynthia** [comment]
As pointed out, this has already been brought up and the conclusion was that it is incompatible with the features I want to implement in PronounDB and how PronounDB fundamentally works.

A custom field means having to monitor user input and watch out for abuse (and considering what PDB is about, hate raids using this would be unfortunately common) and I **absolutely do not want** to deal with that moderation stuff.
