### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by yeSpud** [cyyynthia/pronoundb.org#36]
Looks like the site is offline

<img width="1792" alt="Screen Shot 2021-11-07 at 14 58 21" src="https://user-images.githubusercontent.com/10385195/140665172-75806944-8393-4a5b-a3ed-5b49096adc1c.png">

This seems to be a repeat of #31

**Comment by cyyynthia** [comment]
The website is operating as usual.
