### ISSUE TITLE
sha512 hash error on /me

### ISSUE THREAD

**Issue by tazz4843** [cyyynthia/pronoundb.org#37]
After successfully authenticating with either GitHub or Discord, and redirecting to /me, the page loads but never renders any content, and console has this error: `None of the "sha512" hashes in the integrity attribute match the content of the subresource.`

Not sure what's up here. I'm using Firefox 94.0 on Linux.

**Comment by cyyynthia** [comment]
Odd, everything works fine for me here. Does refreshing with Ctrl+F5 help in any way?

**Comment by cyyynthia** [comment]
It seems like previous build had some integrity hash issues for some reason... I just published a new build which should hopefully fix this issue. Let me know if it still isn't fixed after clearing cache for pronoundb.org on your browser.

**Comment by tazz4843** [comment]
Works fine now, thanks!
