### ISSUE TITLE
Firefox permissions

### ISSUE THREAD

**Issue by AliceDTRH** [cyyynthia/pronoundb.org#38]
I noticed the extension now requires access to all tabs on Firefox.
I was wondering why this was needed but I couldn't find the commit where it was changed.
Could you point me in the right direction?

Kind regards,
Alice

**Comment by cyyynthia** [comment]
Hello,

The `tabs` permission change was introduced [early in the extension rewrite](https://github.com/cyyynthia/pronoundb.org/commit/20d090f90583260857b887bff5c8294fa8f5b9b0) and is used only [here](https://github.com/cyyynthia/pronoundb.org/blob/286a6d46c9fdeeb3044d13d0e6211e61a3981b5b/packages/extension/src/modules/index.ts#L48).

The extension uses URLs to determine whether it should load an integration or not, and this also applies for the popout screen. Unfortunately for principle of least privilege, getting the URL of the currently selected tab (or any tab for that matter) in a popout [requires the `tabs` permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) which is rather broad sadly.

**Comment by cyyynthia** [comment]
Actually, looking back at the docs it seems I completely overlooked the `activeTab` permission, whoops!

I'll loosen the permission requirements and publish a new version shortly.

**Comment by cyyynthia** [comment]
The new version of the extension (0.6.1) should go live on AMO shortly. Thanks for the heads up!

**Comment by AliceDTRH** [comment]
Thank you :)
