### ISSUE TITLE
Blank Page on Website after Logging in [Chrome, Firefox]

### ISSUE THREAD

**Issue by sp96296** [cyyynthia/pronoundb.org#39]
Logging into the website results in a blank page with no options. This occurs in both Firefox (96.0a1) and Chrome (98.0.4723.0). The extension is installed and enabled on both browsers.

![image](https://user-images.githubusercontent.com/36968514/142927586-1af4548e-b7f1-4620-b0d8-a5f9b0f253bc.png)

**Comment by cyyynthia** [comment]
It seems like the JavaScript file is not loading properly, try refreshing with `Ctrl+F5` and see if it helps

**Comment by cyyynthia** [comment]
For good measure, I just initiated a full cache clear on Cloudflare, in case any bad data got stuck in their cache. If you already tried again, consider trying again in 5-10 minutes, see if it still isn't working. Maybe also try purging all your browser data for pronoundb.org.

**Comment by knock2one** [comment]
It's working now! It wasn't working on my phone since yesterday, and I thought it was just a mobile thing, but no, it's working fine there too!

**Comment by cyyynthia** [comment]
Closing this as solved, feel free to leave a comment if the problem still persists.
