### ISSUE TITLE
Twitch extension isn't fully compatible with FFZ

### ISSUE THREAD

**Issue by Vivelin** [cyyynthia/pronoundb.org#40]
I don't get any pronouns in chat with this extension. If I allow this extension to run in an InPrivate window, the badges show up in chat as expected. 

It looks like the [FrankerFaceZ](https://www.frankerfacez.com/) extension changes the chat message layout which seems to break the chat part of the Twitch part of this extension. From a quick glance at the code, it looks like the `data-a-user` attribute is missing (among others)?

The user popout and 'about' section seem to work fine.

**Comment by cyyynthia** [comment]
After a quick check, it seems FFZ completely replaces the whole chat component with its own implementation, which breaks more than just the lack of `data-a-user`. However, FFZ devs are kind enough to expose the user id as a data prop, so it shouldn't be an issue. I just need to detect the presence of FFZ and adapt slightly my approach to fetch/append pronouns in this scenario.

I'll look into it a bit later, compatibility with other extensions isn't my first priority but the fix should be relatively simple. Ideally I'd like to have more than simply this change to publish a new version, as releasing updates in extension stores is rather annoying especially considering Chrome's insane review times of weeks - it's the only store where 0.6.0 (and 0.6.1) aren't available :/

**Comment by cyyynthia** [comment]
Version 0.7.0 (with FFZ compatibility) is now available in AMO and will go live on other extension stores in the following days. 🎉
