### ISSUE TITLE
Add extra attributes to inserted DOM element on Twitch

### ISSUE THREAD

**Issue by zoetrope69** [cyyynthia/pronoundb.org#41]
I'd like to be able to change the styling of the badge added in on Twitch but there currently isn't any selector that match it specifically.

What do you think to adding a data attribute like `data-provider="pronoundb"`? I can submit a PR adding it if you think it's a good idea.

**Comment by cyyynthia** [comment]
I'm not opposed to adding ways to select PronounDB generated elements, I think adding a class name would be a bit better than a data attribute, easier to query and I don't think it'd cause any issues. Feel free to PR!

**Comment by zoetrope69** [comment]
Cool I'll open a PR with a class!

**Comment by cyyynthia** [comment]
Version 0.7.0 (with class names on elements (Twitch only)) is now available in AMO and will go live on other extension stores in the following days. 🎉

**Comment by zoetrope69** [comment]
Thank you @cyyynthia !
