### ISSUE TITLE
Login page incorrect icons and text for options

### ISSUE THREAD

**Issue by zoetrope69** [cyyynthia/pronoundb.org#42]
![image](https://user-images.githubusercontent.com/2591901/143488080-fb1b3ac5-c694-4404-9e8e-6aabb8893f92.png)

Steps to replicate:

1. Go into incognitio mode Firefox
2. Go to https://pronoundb.org/login
3. You should see a list of options icons and text matching correctly.
4. What you get is incorrect icon for Github and incorrect text for Twitch and Twitter.

**Comment by cyyynthia** [comment]
After a quick check this seems to be an issue that only occurs when rendered by the server (when arriving on the page, or refreshing), but when rendered by the client (during navigation) there seem to be no issues, which is rather weird considering both run exactly the same code. It happens on the register and link page too (which makes sense as it's internally the same page with different text). I'll give that a look soon.

**Comment by zoetrope69** [comment]
Yeah, I had a quick look and was confused how it'd be broken.

**Comment by cyyynthia** [comment]
This has been fixed in 939e616. Both the server and the client rendered the correct icons and labels, but due to the website being aware of the presence of the extension or not, the state for the Facebook login button differed causing vdom trees not to match.
