### ISSUE TITLE
Feature: Dark mode in pop-up (with existing bugs noted)

### ISSUE THREAD

**Issue by zoetrope69** [cyyynthia/pronoundb.org#44]
Tested in Firefox.

I think I'm right in this being a feature but if while it's not implemented there are a few bugs from using shared styling:

![image](https://user-images.githubusercontent.com/2591901/143491994-53f18bca-6fbe-4437-abd1-a0b85f6ee0a1.png)

Here the link is assuming we're in dark mode and so the colour contrast is much too low.

**Comment by cyyynthia** [comment]
Yeaaah that's a problem, the extension is currently not responding to the preferred color scheme, however the website does and this specific element is the only shared style which therefore responds to preferred colors. I recall ditching dark mode support for a reason when I started the extension rewrite but I can't remember why... Considering it works I don't see a valid reason not to implement it, so I'll work on that!

**Comment by cyyynthia** [comment]
Dark theme is ready and will land in next update! 🎉 

![preview](https://user-images.githubusercontent.com/9999055/143586962-8532d8cc-bd22-4d9b-acf8-bcab46873c94.png)

**Comment by cyyynthia** [comment]
Version 0.7.0 (with dark theme) is now available in AMO and will go live on other extension stores in the following days. 🎉
