### ISSUE TITLE
Discord: Pronouns disappear when switching tabs on user profile

### ISSUE THREAD

**Issue by EnbyAce** [cyyynthia/pronoundb.org#46]
I'm bad at explaining things so I'll try to mostly use images.

First you go to someone's profile:
![image](https://user-images.githubusercontent.com/39498818/146683185-140a5869-f0a0-4658-aa73-5aba621aca1d.png)

Move to another tab:
![image](https://user-images.githubusercontent.com/39498818/146683227-14223311-3867-4bb0-9c80-85ced891425d.png)

Go back to the user info tab:
![image](https://user-images.githubusercontent.com/39498818/146683239-fad9357e-e273-4793-aaa3-e9e257b4ae08.png)

**Comment by cyyynthia** [comment]
I got what you meant, I changed the title to reflect the bug's cause. Nice catch!

**Comment by cyyynthia** [comment]
Version 0.8.0 is currently pending review in all stores; should be coming to Firefox very shortly, Chrome in a few hours and Edge in a few days.

**Comment by EnbyAce** [comment]
What about in BetterDiscord's plugin repo?

**Comment by cyyynthia** [comment]
This is not maintained by me and you will have to reach the original author of it.
