### ISSUE TITLE
Twitter on (fork of) Firefox: Dupes of pronouns showing

### ISSUE THREAD

**Issue by tacohitbox** [cyyynthia/pronoundb.org#47]
# Description
Normally browsing twitter, sometimes pronouns appear twice. I don't know what *exactly* causes it, but it happens even if you view a profile for the first time.

Edit: I don't know if this changes much, but the fork I use is Librewolf.

# Screenshots
![Pronouns showing twice on a user profile](https://user-images.githubusercontent.com/87399016/146839243-86bb0ce6-fa06-4dce-bfd6-3282e5a431a5.png)

![Pronouns showing twice in user module](https://user-images.githubusercontent.com/87399016/146839346-5b79ffa2-eaef-4319-b6c6-d99031680be0.png)

**Comment by cyyynthia** [comment]
This has been fixed in c4b7350b2b619f44a5070844fb51dc2e692d81ff. Version 0.8.0 is currently pending review in all stores; should be coming to Firefox very shortly, Chrome in a few hours and Edge in a few days.
