### ISSUE TITLE
Twitter (Firefox/Chromium): Pronouns appear under botsentinel ratings

### ISSUE THREAD

**Issue by BurnerWah** [cyyynthia/pronoundb.org#48]
Tested on Firefox & Chromium. This occurs when also using the botsentinel extension for either browser.

Expected behavior: Pronouns appear in the same line as other tweet/user info, and the botsentinel rating shows up on the next line.

A demo of what that would look like:

![](https://user-images.githubusercontent.com/10004812/147415865-4f1cff8d-4a62-4085-bd4f-83b13907b083.png)

Actual behavior: Pronouns appear on a separate line, underneath the botsentinel rating.

![](https://user-images.githubusercontent.com/10004812/147415852-f647a63e-5797-4ed6-9d8a-efc023e4b348.png)

---

What I'm pretty sure is happening is that botsentinel and pronoundb both just place their elements as the last one in the list. Since botsentinel's ratings show up on a second line, and the element also takes up that whole line, pronouns end up on a third line.

So ensuring that pronouns only get inserted after elements that are actually from twitter would probably fix this.

For quick access, here's the botsentinel extension for [firefox](https://addons.mozilla.org/en-US/firefox/addon/bot-sentinel/) and [chrome](https://chrome.google.com/webstore/detail/bot-sentinel/eadmnplpcakhnmjbaioeholpakbknhgc)

**Comment by cyyynthia** [comment]
Version 0.8.0 is currently pending review in all stores; should be coming to Firefox very shortly, Chrome in a few hours and Edge in a few days.
