### ISSUE TITLE
Add linking Minecraft account

### ISSUE THREAD

**Issue by EnbyAce** [cyyynthia/pronoundb.org#50]
Just a random thought I had, I'll be able to make a plugin to mention the pronouns in chat, I just need to be able to use the `/api/v1/lookup` endpoint knowing the UUID of the player

**Comment by cyyynthia** [comment]
While I like the idea of making a Minecraft plugin (or maybe client-side mod? or both? giving out an idea here), it'd be the first type of accounts which do not receive a corresponding module in the extension (or any form of official integration).

I don't have any problem with that, but I'm wondering if it'd be necessary to have a distinction within the UI, or some note to it..

**Comment by EnbyAce** [comment]
As long as I can use the API endpoint to get the pronouns it's fine to me.
I don't think a note is necessary, but certainly useful.

**Comment by EnbyAce** [comment]
Hey uhh @cyyynthia? How do I build the packages? I haven't even modified anything yet and running `npx tsc` in `./packages/api/` already returns 1406 errors 😅
I have already tried installing node packages with `npm i` but that didn't solve a thing.

**Comment by cyyynthia** [comment]
This project uses pnpm for dependency management and scripts.

**Comment by cyyynthia** [comment]
Linking to Minecraft accounts (via Xbox Live only) is now supported 🎉 

`https://pronoundb.org/api/v1/lookup?platform=minecraft&id=63d08e0c-1b0a-4afa-a545-aa5088c48d7a`
