### ISSUE TITLE
Pronouns are incorrectly assigned on retweets (Twitter)

### ISSUE THREAD

**Issue by BluSpring** [cyyynthia/pronoundb.org#55]
The account retweeting the tweet gets their pronouns assigned on the tweet, and not the person's who originally tweeted it.

![image](https://user-images.githubusercontent.com/20620191/162567543-a61e8e28-1656-4470-ba5e-1662b3ef252f.png)

![image](https://user-images.githubusercontent.com/20620191/162567480-8e613f9b-634b-4c5b-821e-d62b81dd0874.png)
![image](https://user-images.githubusercontent.com/20620191/162567489-51915a1b-7607-4bf1-8ac4-199a1f54efc6.png)

**Comment by cyyynthia** [comment]
A fix has been pushed as of cfe5a6f294940a109e2e46353edd1ead9c455a02 for this issue. The extension is pending rollout in all stores; the fix should be live within minutes on Firefox, later today on Chrome and in a few days on Edge. I'll close this once I get the confirmation the update is live everywhere.

**Comment by cyyynthia** [comment]
The fix should be available everywhere now 🎉
