### ISSUE TITLE
Discord module causing incorrect formatting in "About Me" section

### ISSUE THREAD

**Issue by catfox56** [cyyynthia/pronoundb.org#56]
Enabling the Discord module causes the text in the "About Me" section of everyone's profile to become squished on the right side of the popup box, causing the text box to be mostly empty and usually results in the bio being mostly unreadable, however when I disable the PronounDB discord module it returns to normal. This is on PronounDB v0.8.1 and Google Chrome version 100.0.4896.75. Really love this extension btw!

**Comment by cyyynthia** [comment]
The update (0.9.0) is now available in extension stores
