### ISSUE TITLE
[BUG][POWERCOD] Text channels do not load when powercord plugin is enabled

### ISSUE THREAD

**Issue by BenSegal855** [cyyynthia/pronoundb.org#6]
The title pretty much says it all. When the PronounDB plugin is active, text channels display no messages whatsoever. This effectively makes the plugin unusable. 

**Build info**
PronounDB commit: 50a5f3943fbcbd0c45eb120f50d86e5af6048db3
Powercord version: 7813234
Canary version: 8a96292
OS: Windows 10

**Comment by cyyynthia** [comment]
A fix has been issued here: https://github.com/cyyynthia/pronoundb-powercord/commit/93c7ced43abb295fe7228dfb0d1b2124cdf2726a
