### ISSUE TITLE
Crashes when Clicking on Profiles

### ISSUE THREAD

**Issue by kn1vesout** [cyyynthia/pronoundb.org#61]
Whenever the plugin is turned on, clicking on someone's profile will crash discord. Turning it off and back on will create the ability to click on profiles without it crashing, however pronouns are not able to be changed.
![crashed discord](https://user-images.githubusercontent.com/105134118/167275741-7a164d83-5586-44da-86bf-3b7be94b53c3.png)

**Comment by cyyynthia** [comment]
This seem to be an issue with a plugin for a Discord client mod, which is separate from the main repository. You should report this issue to the appropriate place, on the repository of the plugin you're using.
