### ISSUE TITLE
Website seems to be wrong

### ISSUE THREAD

**Issue by muluffel** [cyyynthia/pronoundb.org#63]
Hi There,
the website pronoundb.org seems to have the stylesheet missing. Also, neither clicking "Login" nor clicking "Create Account" does anything.

**Comment by cyyynthia** [comment]
I *just* rolled out an update to the website, so it's possible that you had a bad timing and loaded the website during the rollout. Is the website still broken on your end?

**Comment by muluffel** [comment]
Yep, works again. Thanks for the quick response and for that lovely project <3
