### ISSUE TITLE
he/any and she/any pronouns

### ISSUE THREAD

**Issue by Gaming32** [cyyynthia/pronoundb.org#67]
What's said in the title. I personally go by he/any, which is why I bring this up.

**Comment by cyyynthia** [comment]
It's been a while, but I've been doing work on APIv2 and this feature is ready as part of the big update that's upcoming. Additional information can be found on the APIv2 issue #68.

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/96924c70-573a-4e7a-ad22-b7c022c39b6f)

**Comment by cyyynthia** [comment]
This is now possible! You can set your sets to such a configuration on the website now, and the update to the extension adding support for these configurations is out. 🎉
