### ISSUE TITLE
on discord, using the browser plugin, pronouns do not seem to be re-added to old messages.

### ISSUE THREAD

**Issue by heav-4** [cyyynthia/pronoundb.org#70]
when you exit a channel and re-enter it for instance, the pronouns disappear on old messages.
here's a video: https://cdn.discordapp.com/attachments/198130613759246337/1008031734052425759/2022-08-13_15-17-11.mp4

**Comment by cyyynthia** [comment]
This bug has been fixed in dadf79e9742d13efed7033848e7d4e12c79fa6e9, however this patch has not yet been published to extension stores.

**Comment by cyyynthia** [comment]
Version 0.10.0 is currently rolling out with the fix for this bug. 🎉
