### ISSUE TITLE
Modrinth integration looks funny with some options selected

### ISSUE THREAD

**Issue by triphora** [cyyynthia/pronoundb.org#76]
![](https://cdn.discordapp.com/attachments/848329986577399818/1046953596576596009/image.png)
On this page: https://modrinth.com/user/Prospector
"**Any pronouns** pronouns" should just be "**Any** pronouns"

**Comment by Prospector** [comment]
Same applies for all of the longer text options

![image](https://user-images.githubusercontent.com/6166773/204413048-01dc577e-e35c-43a9-b46e-b9d5d1847282.png)
