### ISSUE TITLE
Further explanations into pronouns

### ISSUE THREAD

**Issue by ShadiestGoat** [cyyynthia/pronoundb.org#77]
Hello! I would love it if there was some sort of explanation to some pronouns in the docs. 

For example, `he/it` isn't quite understandable to me. Or, for another example, it took me a bit of time to understand what `she/he` is vs `he/she`.

**Comment by NoPlagiarism** [comment]
https://en.pronouns.page/

**Comment by cyyynthia** [comment]
Pronouns Page is a great resource but I don't think there'd be harm in adding a quick guide for understanding the basics of how pronouns work for people unsure what it's all about.

Here are the answer to your questions in the meantime:
 - "combined sets", like he/it, he/they, ... mean the person is fine being called either set. The long form would be "he/him or it/its".
 - The order is kind of here to set preference. he/they people might prefer he, while they/he people might prefer they - but both of these groups are fine being called either of the sets.

I can look into putting together a page that explains these basics, and which links back to pronouns page for more in-depth explanations.

**Comment by ShadiestGoat** [comment]
Ah thank you for the explanations! I'll check out pronoun page for further reading as well then ^^

**Comment by cyyynthia** [comment]
I made a very short page, with the intent to be straight to the goal and include all one needs to get started.

Currently deployed on the (ephemeral) beta website: https://beta.pronoundb.org/pronouns-101 - Let me know if you feel like anything else might be worth adding. Issue will be closed once it's fully deployed on the main website 👍🏻

**Comment by ShadiestGoat** [comment]
Seems to be all the needed info!
