### ISSUE TITLE
Pronouns no longer display on Twitch.tv?

### ISSUE THREAD

**Issue by Lylythii** [cyyynthia/pronoundb.org#79]
Noticed this morning that Twitch no longer displays pronouns in chat or on profiles.

**Comment by cyyynthia** [comment]
It seems I have messed up the permissions requested by the extension... 🥲

I'll roll out an update in a bit.

**Comment by cyyynthia** [comment]
fixed in 521ca51a346a208309e5713efa411cd34bf7d361
