### ISSUE TITLE
Mobile footer is jank

### ISSUE THREAD

**Issue by BenSegal855** [cyyynthia/pronoundb.org#8]
The homepage footer on mobile looks quite jank. The below screenshot was taken on an ios device using safari. As you can see, the normal footer text is overlapping with the page contents.
![](https://cdn.discordapp.com/attachments/748714750463967333/790040381910679552/image0.png)

**Comment by cyyynthia** [comment]
Seems like it's a Safari-only issue, if people are willing to give a closer look and try to fix it I'd appreciate it since I can't really test out this environment

**Comment by BenSegal855** [comment]
I just checked again and the footer seems to look much better now as seen below. Ill close this issue for now and open it up again if the jankyness returns. 
![](https://cdn.discordapp.com/attachments/748714750463967333/794276178873024583/image0.png)
