### ISSUE TITLE
Small Extension Window Not Displaying Anything

### ISSUE THREAD

**Issue by Aikerin** [cyyynthia/pronoundb.org#80]
Hello

I'm using Opera GX - with a Chrome Web Store extension installer extension (complicated-sounding, I know) - and the pop-up in the extensions area has just gone completely blank in the last couple days. I'm no longer able to see anything in it, and I'm not sure if it has anything to do with the fact that I'm using Opera GX or not. Please let me know if you might know the cause of this issue, and if it can be fixed.

Thanks!
- Joe (currently trying out she/her)

**Comment by NoPlagiarism** [comment]
> (currently trying out she/her)

You can just connect your GitHub to pronoundb :D 

Same on FireFox + Opera GX

Extension ver: `0.11.4`

**Comment by cyyynthia** [comment]
Yup, it seems the extension build broke unexpectedly due to some mismatches between internal packages. I'll roll out an update very soon; it should be live within the next few minutes (considering you depend on the Chrome Web Store, it should take ~15-20mins from now).

**Comment by cyyynthia** [comment]
Closing this as the extension has been published & reviewed.

Thanks for using PronounDB, and I hope you'll find pronouns that make you happy to live by! :D ❤️
