### ISSUE TITLE
Authentication does not work on Safari and iOS browsers (WebKit)

### ISSUE THREAD

**Issue by nyathea** [cyyynthia/pronoundb.org#89]
Whenever i try to link my discord i get “An unknown error occurred while authenticating with the third party service.” And it won’t let me do anything else.

**Comment by cyyynthia** [comment]
The only 2 cases where this should occur are:
 a) Discord is having an outage - doesn't seem to be the case
 b) Your browser isn't sending back the appropriate cookies after authorizing with Discord. Do you happen to have cookies disabled on your browser?

Cookies are required for the authorization to succeed, or it will internally detect an anomaly raising this error.

**Comment by pinheadtf2** [comment]
I’m having this issue with all services, using Firefox for iOS 16

I believe cookies are on as I can do service connections and logins elsewhere without issue

**Comment by cyyynthia** [comment]
Yeah, after chatting on Discord with someone else about the same issue, it seems there is an issue with authenticating via iOS (and considering the nature of the bug the browser probably won't matter as they're all using the same engine under the hood which seems to behave differently than Blink or Gecko).

I'll investigate the issue in a bit, it's probably something silly that I can fix without too much troubles.

**Comment by pinhead-tf2** [comment]
Sounds about right, hopefully we can get different browser engines soon

If you need a tester, feel free to add me: pinhead#4946

**Comment by OIRNOIR** [comment]
The same thing happens for me on Safari for MacOS 13. Firefox worked though. Once I had managed to register my account on firefox, I copied the token cookie to safari via devtools and that allowed me to log in on safari.
