### ISSUE TITLE
new 7tv update broke pronouns for twitch chat

### ISSUE THREAD

**Issue by solstacoded** [cyyynthia/pronoundb.org#92]
the 7tv extension received an update recently, and my pronouns no longer show up in twitch chat. i did a little digging and it seems 7tv has completely rebuilt the twitch chat from scratch

(screenshot of the html)
![image](https://user-images.githubusercontent.com/52147022/229347923-a87e06fb-5aff-4394-a960-59999d1ceec6.png)

**Comment by cyyynthia** [comment]
I've started looking into this, but it's actually quite a difficult problem to tackle. While FFZ's injection was friendly and exposed data that I needed, 7TV's injection completely withdraws control and keeps data in a privately-owned state I can't seem to be able to poke into. It seems their injection methods also prevents Twitch's own stores from being populated, making the ID resolve task difficult.

I'll keep looking for ways to extract the data I need, but the task appears to be quite tough.
