### ISSUE TITLE
Add was/were

### ISSUE THREAD

**Issue by Epenko1337** [cyyynthia/pronoundb.org#93]
Was/were pronoun supposed to be here too!

**Comment by 9021007** [comment]
![image](https://user-images.githubusercontent.com/24487638/233215150-b869a3a5-d017-460e-a2d1-40f11a9764fc.jpeg)

**Comment by Epenko1337** [comment]
you have insulted me

**Comment by NoPlagiarism** [comment]
Бля, не страдай хуйнёй

He's "troll", forget it and close pls
