### ISSUE TITLE
[Feature Request] fae/faer, or a user input box for neopronouns

### ISSUE THREAD

**Issue by Mokura** [cyyynthia/pronoundb.org#94]
As mentioned in the title - I don't expect anyone to code in every possible NP, but a String variable to put in your own pronoun choices might be nice (depending on backend feasibility, of course.)

**Comment by cyyynthia** [comment]
Both of these are addressed in the [README](https://github.com/cyyynthia/pronoundb.org#faq). Support for neos is planned, and there will never be a free-text input due to risk of abuse and moderation requirements.

**Comment by Mokura** [comment]
Thank you, I must have missed it.  I did search the issues first, and I should have known better wrt text fields.
