### ISSUE TITLE
Adding API For Other Websites

### ISSUE THREAD

**Issue by wrentmc** [cyyynthia/pronoundb.org#95]
Is it possible to add a feature where website creators can specify in the HTML of our webpage what pronouns to use?
For example, we would click the extension, and it would show the website owner's pronouns.
Thanks in advance!

**Comment by 9021007** [comment]
https://pronoundb.org/docs

**Comment by wrentmc** [comment]
> https://pronoundb.org/docs

Hey there! I checked the docs and still don't see anything that can help with this. Would you like more information?

**Comment by 9021007** [comment]
You can just have it grab your current setting and add it to the page itself with JavaScript

**Comment by NoPlagiarism** [comment]
The best you can do now - use linked accounts of supported systems.

Btw, would be cool, if there would be a possibility to get pronouns from pronoundb acc id. It should do the trick, I guess

**Comment by cyyynthia** [comment]
I'm unsure what would be the use case here. I've seen people use the PronounDB API to fetch pronouns to show on their own pages, but I'm unsure what you're trying to achieve here.

**Comment by wrentmc** [comment]
> I'm unsure what would be the use case here.

Hi there! The use case would be that users could add support for their own pages.

Think of a website where users can host their own pages. I have one of them. In this case, users would have a button to import their extension preferences (of course, the server owner would have to add a header or flag in the source code). If we could add this, it would be awesome. Thanks for your time!

**Comment by cyyynthia** [comment]
The extension cannot inject into arbitrary pages; it is limited to the list of supported websites as a security measure from the browser extension platform. With that in mind, I still am very confused as what you mean.

**Comment by cyyynthia** [comment]
Without further information I'll close this issue.
